# Generated by Django 4.2.27 on 2026-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_theme_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='welcome_message',
            field=models.TextField(blank=True, help_text="Message pour la salle d'attente", null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='welcome_title',
            field=models.CharField(blank=True, help_text="Titre pour la salle d'attente", max_length=200, null=True),
        ),
    ]
