# Generated by Django 4.2.27 on 2026-02-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_question_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
