# Generated by Django 4.2.27 on 2026-02-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_panel_welcome_message_panel_welcome_title'),
    ]

    operations = [
    ]
