# Generated by Django 4.2.27 on 2026-02-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0004_remove_slug_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
